CREATE TABLE IF NOT EXISTS address (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HOUSE_NAME_OR_NUMBER VARCHAR(250) NOT NULL,
    ADDRESS_LINE_1 VARCHAR(250) NOT NULL,
    ADDRESS_LINE_2 VARCHAR(250),
    CITY VARCHAR(250),
    POSTCODE VARCHAR(250),
    COUNTRY VARCHAR(250)
);